Insert into State (Country_Id, State_Name)
values
('1', 'Badakhshan'),
('1', 'Badghis'),
('1', 'Baghlan'),
('2', 'Berat'),
('2', 'Diber'),
('2','Durres'),
('3', 'Adrar'),
('3', 'Blida'),
('3', 'Tipaza'),
('4', 'Canillo'),
('4', 'Ordino'),
('5', 'Tasmania'),
('5', 'Victoria'),
('6', 'Burgenland'),
('6', 'Tirol'),
('7', 'Bahia'),
('7', 'Roraima'),
('8', 'Dhaka'),
('9', 'Jilin'),
('10', 'Atacama'),
('11', 'Capital'),
('12', 'Suhaj'),
('13', 'Tigray'),
('14', 'Auvergne'),
('15','South Savo'),
('16', 'Bremen'),
('17', 'Ajaria'),
('18', 'Crete'),
('19', 'Eastern District'),
('20', 'BaranyaMegye'),
('21', 'Kerala'),
('22', 'Cavan'),
('23', 'Akita'),
('24', 'Hawalli'),
('25', 'Central'),
('26', 'Diekirch'),
('27', 'Colima'),
('28', 'Eastern'),
('29', 'Dhofar'),
('30', 'Lodzkie'),
('31', 'Al Khawr'),
('32', 'Altay'),
('33', 'Free State'),
('34', 'Bern'),
('35', 'Idlib'),
('36', 'Chai Nat'),
('37', 'Alaska'),
('37', 'Texas'),
('37', 'New York'),
('37', 'California'),
('38', 'Abim'),
('39', 'Bac Can'),
('40', 'Ataq'),
('41', 'Bulawayo'),
('37', 'New Jersey');