insert into City (State_Id, City_Name)
values
('1', 'Jurm'),
('2' ,'Abbakhsh'),
('3', 'Baglan'),
('4', 'Berat'),
('5', 'Burrel'),
('6', 'Durres'),
('7', 'Algiers'),
('8', 'Amsthas'),
('9', 'Aboucha'),
('10', 'Canillo'),
('11','Ordino'),
('12', 'Hobart'),
('13', 'Melbourne'),
('14', 'Eisenstadt'),
('47', 'Anchorage'),
('47', 'Fairbanks'),
('47', 'College'),
('47', 'Kodiak'),
('47', 'Meadow Lakes'),
('48', 'Houston'),
('48', 'Dallas'),
('48', 'Austin'),
('48', 'Fort Worth'),
('49', 'New York'),
('49', 'Buffalo'),
('49', 'Rochester'),
('49', 'Syracuse'),
('49', 'Albany'),
('50', 'Los Angeles'),
('50', 'San Diego'),
('50', 'San Francisco'),
('50', 'Oakland'),
('50', 'Sacremento');
--('56', 'Newark');
