insert into Country (Country_Name)
values 
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Australia'),
('Austria'),
('Brazil'),
('Bangladesh'),
('China'),
('Chile'),
('Denmark'),
('Egypt'),
('Ethiopia'),
('France'),
('Finland'),
('Germany'),
('Georgia'),
('Greece'),
('Hong Kong'),
('Hungary'),
('India'),
('Ireland'),
('Japan'),
('Kuwait'),
('Kenya'),
('Luxembourg'),
('Mexico'),
('Nepal'),
('Oman'),
('Poland'),
('Qatar'),
('Russia'),
('South Africa'),
('Switzerland'),
('Syria'),
('Thailand'),
('United States'),
('Uganda'),
('Vietnam'),
('Yemen'),
('Zimbabwe');
